title: NLP workflows for the Digital Humanities
author: Tess Dejaeghere
email: tess.dejaeghere@ugent.be
description: > # this means to ignore newlines until "baseurl:"
  Bridging the gap between NLP and DH by creating understandable, transparent and durable workflows!

# social links
twitter_username: DejaeghereTess # DO NOT include the @ character, or else the build will fail!
github_username:  TessDejaeghere # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
